### ISSUE TITLE
Problem facing in CCS during the compilation by using your project

### ISSUE THREAD

**Issue by Keerthivasan-coder** [Dasch0/ei-ti154-remote-monitor#1]
Hi @Dasch0 
I have imported your project in my code composer studio and tried to bulid the project by following the given procedure.
During the compilation, I've been facing the following errors in gmake, makefiles.
Kindly assist me regarding the project.

Description
gmake: *** [../src/sysbios/rom_sysbios.aem4f] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake: *** [build-1322531727] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake: *** [E:/SS/ei-ti154-remote-monitor-main/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/src/makefile.libs:57: E:/SS/ei-ti154-remote-monitor-main/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/src/sysbios/rom_sysbios.aem4f] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake: Target 'all' not remade because of errors.	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [build-1322531727-inproc] Error 1	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [m3_Hwi_asm_switch.obj] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [m3_Hwi_asm.obj] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [m3_IntrinsicsSupport_asm.obj] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [m3_TaskSupport_asm.obj] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [makefile:60: rom_sysbios.obj] Error 127	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: *** [rom_sysbios.obj] Error 2	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
gmake[1]: Target 'all' not remade because of errors.	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
recipe for target '../src/sysbios/rom_sysbios.aem4f' failed	makefile.libs	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/src	line 56	C/C++ Problem
recipe for target 'build-1322531727' failed	subdir_rules.mk	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 9	C/C++ Problem
recipe for target 'build-1322531727-inproc' failed	subdir_rules.mk	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 12	C/C++ Problem
recipe for target 'm3_Hwi_asm_switch.obj' failed	makefile	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 45	C/C++ Problem
recipe for target 'm3_Hwi_asm.obj' failed	makefile	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 41	C/C++ Problem
recipe for target 'm3_IntrinsicsSupport_asm.obj' failed	makefile	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 49	C/C++ Problem
recipe for target 'm3_TaskSupport_asm.obj' failed	makefile	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 53	C/C++ Problem
recipe for target 'rom_sysbios.obj' failed	makefile	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang/Release	line 58	C/C++ Problem
xdc.cfg.SourceDir : Build of generated source libraries failed: exit status = 2:	.xdchelp	/ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang	line 211	C/C++ Problem
xdctools_3_62_01_16_core\gmake.exe: *** [package/cfg/app_pem4f.xdl] Deleting file 'package/cfg/app_pem4f.c'	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
xdctools_3_62_01_16_core\gmake.exe: *** [package/cfg/app_pem4f.xdl] Deleting file 'package/cfg/app_pem4f.h'	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem
xdctools_3_62_01_16_core\gmake.exe: *** Deleting file 'package/cfg/app_pem4f.xdl'	ei_sensor_CC1352P1_LAUNCHXL_tirtos_ticlang		 	C/C++ Problem

**Comment by Dasch0** [comment]
Hi, I've fixed this with the same commit fixing #2. See the comment there for details on the issue.
